[project]
name = "student-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "udaynarayansingh725-sys", email = "udaynarayansingh725@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
student-management-system = "student_management_system:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
